python36 Data_challenge.py